### ISSUE TITLE
MRTK Integration

### ISSUE THREAD

**Issue by SashelI** [magicleap/MagicLeapXRKeyboard#2]
Hi, I was looking for a system keyboard for a MRTK 2.8 app and found this one, except it doesn't recognize MRTK Inputs. The hand ray goes through the object. I have tried implementing the IMixedRealityPointerHandler into KeyboardKey.cs, but it still doesn't work. Tried adding a nearinteractiontouchableUI on the key prefab as well.

Am I missing something ?

Thanks

**Comment by kbabilinski** [comment]
You are correct, this keyboard does not work with MRTK out of the box and requires some modification. I'm unable to give you the steps needed to convert the keyboard to work with MRTK but I can tell you that the package uses the generic Unity UI Input events to trigger the key presses. I am also aware that other developers have had success using this package with MRTK but I do not know the specifics. If you are new to converting standard Unity UI to support MRTK 2.8 input you can use the sample virtual keyboard provided in the MRTK examples.

Note, MRTK 3 support is on our roadmap but we do not have an estimated date on when it will be available at this time.

**Comment by SashelI** [comment]
I see, thanks.
